//
// Created by Michał Wawer on 04.12.20.
//

#ifndef POLISHREVERSENOTATIONCALCULATOR_FUNCT_HPP
#define POLISHREVERSENOTATIONCALCULATOR_FUNCT_HPP

template< class >
class Func;


#endif //POLISHREVERSENOTATIONCALCULATOR_FUNCT_HPP
